spring:
  application:
    name: PortierDigital
  devtools:
    add-properties: true
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-exclude: application.yml
      poll-interval: 50ms
      quiet-period: 50ms
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://host.docker.internal:5432/portier_digital
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      data-source-properties:
        useServerPrepStmts: true
        cachePrepStmts: true
        metadataCacheLimit: 1
        transaction-isolation: TRANSACTION_READ_COMMITTED
      leak-detection-threshold: 5000
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
