spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/, file:/usr/local/tomcat/webapps/resources/
  application:
    name: PortierDigital
  devtools:
    add-properties: true
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-exclude: static/images, static/archs
      poll-interval: 150ms
      quiet-period: 100ms
  datasource:
    username: admin
    password: password
    url: jdbc:postgresql://db:5432/portier_digital
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      leak-detection-threshold: 5000
      data-source-properties:
        cachePrepStmts: true
        useServerPrepStmts: true
        metadataCacheLimit: 1
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
      transaction-isolation: TRANSACTION_REPEATABLE_READ
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  output:
    ansi:
      enabled: always
