spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/, 
        file:/apache-tomcat-11.0.4/webapps/resources/portier-digital/,
        file:/usr/local/tomcat/webapps/resources/portier-digital
        file:/home/slj/web/slj.demodev.cc/public_html/
  application:
    name: PortierDigital
  devtools:
    add-properties: true
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-exclude: static/images, static/archs
      poll-interval: 1000ms
      quiet-period: 200ms
  datasource:
    username: admin
    password: password
    url: jdbc:postgresql://db:5432/portier_digital
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      data-source-properties:
        useServerPrepStmts: true
        cachePrepStmts: true
        metadataCacheLimit: 1
        transaction-isolation: TRANSACTION_READ_COMMITTED
      leak-detection-threshold: 5000
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
