name: PortierDigital


services:
  db:
    container_name: postgres-pd
    image: postgres:latest
    networks:
      app-net:
    ports:
      - "5445:5432"
    environment:
      POSTGRES_DB: "portier_digital"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

  app:
    container_name: portier-digital
    depends_on:
      - db
    image: andropcolo/portier-digital:latest
    networks:
      app-net:
    ports:
      - "8088:8080"
    volumes:
      - /home/slj/web/slj.demodev.cc/public_html/resources/portier-digital/:/usr/local/tomcat/webapps/resources/


networks:
  app-net:
    labels:
      - "Portier Digital Special Network"
    driver: bridge
