name: GitHub Actions Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Setup Java JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'oracle' # See 'Supported distributions' for available options
            java-version: '17'
            cache: 'maven'
            cache-dependency-path: pom.xml # optional
        - name: Test with Maven
          run: mvn test