name: Portier Digital Workflows
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
    branches:
      - main


jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
      - name: Test with Maven
        run: mvn test


  build:
    name: Build and Push to DockerHub
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: "pom.xml" # optional
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Maven builds
        run: mvn clean package
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: andropcolo/portier-digital:latest

  recreate:
    name: Remote ssh command
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SPACELAB_HOST }}
          port: '22'
          username: ${{ secrets.SPACELAB_USER }}
          key: ${{ secrets.SPACELAB_SSH_PR_KEY }}
          script: | 
            echo "I\'m working..."
            whoami
            cd ~/web/slj.demodev.cc/public_html/compose
            docker compose up --force-recreate
